#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <stdlib.h>
#include "http.h"

/* Minimal "/" page kept as-is with a tiny login/register UI hint */
const char *INDEX_HTML =
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html; charset=utf-8\r\n"
"Connection: close\r\n"
"\r\n"
"<!doctype html><html><head><meta charset='utf-8'><title>WebSocket Chat</title>"
"<style>"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;margin:0;padding:20px;background:#f5f5f5;}"
".container{max-width:800px;margin:0 auto;background:white;border-radius:8px;box-shadow:0 2px 10px rgba(0,0,0,0.1);overflow:hidden;}"
".header{background:#2c3e50;color:white;padding:20px;text-align:center;}"
".content{padding:20px;}"
".auth-section{margin-bottom:30px;}"
".form-group{margin-bottom:15px;}"
".form-group label{display:block;margin-bottom:5px;font-weight:500;color:#333;}"
".form-group input{width:100%;padding:10px;border:1px solid #ddd;border-radius:4px;font-size:14px;box-sizing:border-box;}"
".form-group input:focus{outline:none;border-color:#3498db;box-shadow:0 0 0 2px rgba(52,152,219,0.2);}"
".btn{background:#3498db;color:white;border:none;padding:10px 20px;border-radius:4px;cursor:pointer;font-size:14px;margin-right:10px;}"
".btn:hover{background:#2980b9;}"
".btn-secondary{background:#95a5a6;}"
".btn-secondary:hover{background:#7f8c8d;}"
".btn-success{background:#27ae60;}"
".btn-success:hover{background:#229954;}"
".btn-danger{background:#e74c3c;}"
".btn-danger:hover{background:#c0392b;}"
".chat-section{border-top:1px solid #eee;padding-top:20px;}"
".user-info{background:#ecf0f1;padding:10px;border-radius:4px;margin-bottom:15px;}"
".chat-log{height:300px;border:1px solid #ddd;padding:10px;overflow-y:auto;background:#fafafa;white-space:pre-wrap;font-family:monospace;font-size:13px;}"
".chat-input{display:flex;gap:10px;margin-top:10px;}"
".chat-input input{flex:1;padding:10px;border:1px solid #ddd;border-radius:4px;}"
".chat-input button{background:#27ae60;color:white;border:none;padding:10px 20px;border-radius:4px;cursor:pointer;}"
".chat-input button:hover{background:#229954;}"
".error{color:#e74c3c;background:#fdf2f2;border:1px solid #fecaca;padding:10px;border-radius:4px;margin-bottom:15px;}"
".success{color:#27ae60;background:#f0f9f0;border:1px solid #c6f6d5;padding:10px;border-radius:4px;margin-bottom:15px;}"
".hidden{display:none;}"
"</style>"
"</head><body>"
"<div class='container'>"
"<div class='header'><h1>WebSocket Chat</h1></div>"
"<div class='content'>"
"<div id='auth-section' class='auth-section'>"
"<div id='login-form'>"
"<h3>Login</h3>"
"<form id='loginForm' method='POST' action='/login'>"
"<div class='form-group'><label for='login-username'>Username:</label><input type='text' id='login-username' name='username' required></div>"
"<div class='form-group'><label for='login-password'>Password:</label><input type='password' id='login-password' name='password' required></div>"
"<button type='submit' class='btn'>Login</button>"
"<button type='button' class='btn btn-secondary' id='need-account-btn'>Need an account?</button>"
"</form>"
"</div>"
"<div id='register-form' class='hidden'>"
"<h3>Register</h3>"
"<form id='registerForm' method='POST' action='/register'>"
"<div class='form-group'><label for='reg-username'>Username (3-32 chars, a-z, 0-9, _):</label><input type='text' id='reg-username' name='username' required pattern='[a-z0-9_]{3,32}'></div>"
"<div class='form-group'><label for='reg-password'>Password (min 8 chars):</label><input type='password' id='reg-password' name='password' required minlength='8'></div>"
"<button type='submit' class='btn btn-success'>Register</button>"
"<button type='button' class='btn btn-secondary' id='have-account-btn'>Already have an account?</button>"
"</form>"
"</div>"
"</div>"
"<div id='user-info' class='user-info hidden'>"
"<span id='username-display'></span>"
"<button class='btn btn-danger' id='logout-btn' style='float:right;'>Logout</button>"
"</div>"
"<div id='chat-section' class='chat-section hidden'>"
"<h3>Chat</h3>"
"<div id='chat-log' class='chat-log'></div>"
"<div class='chat-input'>"
"<input id='msg-input' placeholder='Type your message...' />"
"<button id='send-btn'>Send</button>"
"</div>"
"</div>"
"<div id='message'></div>"
"</div>"
"</div>"
"<script>"
"console.log('Script starting...');"
"let ws = null;"
"let currentUser = null;"
""
"function showLogin() {"
"  console.log('showLogin called');"
"  document.getElementById('login-form').classList.remove('hidden');"
"  document.getElementById('register-form').classList.add('hidden');"
"  clearMessage();"
"}"
""
"function showRegister() {"
"  console.log('showRegister called');"
"  document.getElementById('login-form').classList.add('hidden');"
"  document.getElementById('register-form').classList.remove('hidden');"
"  clearMessage();"
"}"
""
"function showMessage(text, type) {"
"  const msgDiv = document.getElementById('message');"
"  msgDiv.innerHTML = '<div class=\"' + type + '\">' + text + '</div>';"
"  msgDiv.scrollIntoView();"
"}"
""
"function clearMessage() {"
"  document.getElementById('message').innerHTML = '';"
"}"
""
"function setupFormHandlers() {"
"  console.log('Setting up form handlers...');"
"  const loginForm = document.getElementById('loginForm');"
"  const registerForm = document.getElementById('registerForm');"
"  "
"  if (loginForm) {"
"    console.log('Login form found');"
"    loginForm.addEventListener('submit', async function(e) {"
"      console.log('Login form submitted');"
"      e.preventDefault();"
"      const formData = new FormData(this);"
"      const data = new URLSearchParams(formData);"
"      "
"      try {"
"        const response = await fetch('/login', {"
"          method: 'POST',"
"          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },"
"          body: data"
"        });"
"        "
"        console.log('Login response status:', response.status);"
"        if (response.ok) {"
"          showMessage('Login successful!', 'success');"
"          console.log('Login successful, checking auth status...');"
"          setTimeout(function() {"
"            console.log('Calling checkAuthStatus...');"
"            checkAuthStatus();"
"          }, 500);"
"        } else {"
"          showMessage('Login failed. Check your credentials.', 'error');"
"        }"
"      } catch (error) {"
"        showMessage('Login error: ' + error.message, 'error');"
"      }"
"    });"
"  }"
"  "
"  if (registerForm) {"
"    console.log('Register form found');"
"    registerForm.addEventListener('submit', async function(e) {"
"      e.preventDefault();"
"      const formData = new FormData(this);"
"      const data = new URLSearchParams(formData);"
"      "
"      try {"
"        const response = await fetch('/register', {"
"          method: 'POST',"
"          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },"
"          body: data"
"        });"
"        "
"        if (response.ok) {"
"          showMessage('Registration successful! You can now login.', 'success');"
"          setTimeout(showLogin, 1000);"
"        } else if (response.status === 409) {"
"          showMessage('Username already taken. Please choose another.', 'error');"
"        } else {"
"          showMessage('Registration failed. Please check your input.', 'error');"
"        }"
"      } catch (error) {"
"        showMessage('Registration error: ' + error.message, 'error');"
"      }"
"    });"
"  }"
"}"
""
"async function checkAuthStatus() {"
"  console.log('checkAuthStatus called');"
"  try {"
"    const response = await fetch('/me');"
"    console.log('Auth check response status:', response.status);"
"    if (response.ok) {"
"      const user = await response.json();"
"      console.log('User authenticated:', user.username);"
"      currentUser = user.username;"
"      document.getElementById('username-display').textContent = 'Logged in as: ' + user.username;"
"      document.getElementById('auth-section').classList.add('hidden');"
"      document.getElementById('user-info').classList.remove('hidden');"
"      document.getElementById('chat-section').classList.remove('hidden');"
"      console.log('UI updated, connecting WebSocket...');"
"      connectWebSocket();"
"    } else {"
"      console.log('User not authenticated');"
"      currentUser = null;"
"      document.getElementById('auth-section').classList.remove('hidden');"
"      document.getElementById('user-info').classList.add('hidden');"
"      document.getElementById('chat-section').classList.add('hidden');"
"      if (ws) { ws.close(); ws = null; }"
"    }"
"  } catch (error) {"
"    console.error('Auth check failed:', error);"
"  }"
"}"
""
"function connectWebSocket() {"
"  console.log('Connecting to WebSocket...');"
"  if (ws) { ws.close(); }"
"  ws = new WebSocket('ws://' + location.host + '/ws');"
"  "
"  ws.onopen = function() {"
"    console.log('WebSocket connected');"
"    addToChat('[Connected to chat]');"
"  };"
"  "
"  ws.onmessage = function(event) {"
"    console.log('WebSocket message received:', event.data);"
"    addToChat(event.data);"
"  };"
"  "
"  ws.onclose = function() {"
"    console.log('WebSocket disconnected');"
"    addToChat('[Disconnected from chat]');"
"  };"
"  "
"  ws.onerror = function(error) {"
"    console.log('WebSocket error:', error);"
"    addToChat('[WebSocket error]');"
"  };"
"}"
""
"function addToChat(message) {"
"  const chatLog = document.getElementById('chat-log');"
"  chatLog.textContent += message + '\\n';"
"  chatLog.scrollTop = chatLog.scrollHeight;"
"}"
""
"function sendMessage() {"
"  const input = document.getElementById('msg-input');"
"  const message = input.value.trim();"
"  if (message && ws && ws.readyState === WebSocket.OPEN) {"
"    ws.send(message);"
"    input.value = '';"
"  }"
"}"
""
"document.addEventListener('DOMContentLoaded', function() {"
"  console.log('DOM loaded, setting up handlers');"
"  setupFormHandlers();"
"  checkAuthStatus();"
"  "
"  const msgInput = document.getElementById('msg-input');"
"  if (msgInput) {"
"    msgInput.addEventListener('keypress', function(e) {"
"      if (e.key === 'Enter') {"
"        sendMessage();"
"      }"
"    });"
"  }"
"  "
"  const needAccountBtn = document.getElementById('need-account-btn');"
"  if (needAccountBtn) {"
"    console.log('Need account button found');"
"    needAccountBtn.addEventListener('click', function(e) {"
"      e.preventDefault();"
"      console.log('Need account button clicked');"
"      showRegister();"
"    });"
"  } else {"
"    console.log('Need account button NOT found');"
"  }"
"  "
"  const haveAccountBtn = document.getElementById('have-account-btn');"
"  if (haveAccountBtn) {"
"    console.log('Have account button found');"
"    haveAccountBtn.addEventListener('click', function(e) {"
"      e.preventDefault();"
"      console.log('Have account button clicked');"
"      showLogin();"
"    });"
"  } else {"
"    console.log('Have account button NOT found');"
"  }"
"  "
"  const logoutBtn = document.getElementById('logout-btn');"
"  if (logoutBtn) {"
"    console.log('Logout button found');"
"    logoutBtn.addEventListener('click', function(e) {"
"      e.preventDefault();"
"      console.log('Logout button clicked');"
"      logout();"
"    });"
"  }"
"  "
"  const sendBtn = document.getElementById('send-btn');"
"  if (sendBtn) {"
"    console.log('Send button found');"
"    sendBtn.addEventListener('click', function(e) {"
"      e.preventDefault();"
"      console.log('Send button clicked');"
"      sendMessage();"
"    });"
"  }"
"});"
"</script>"
"</body></html>";

const char *BAD_REQUEST =
"HTTP/1.1 400 Bad Request\r\n"
"Connection: close\r\n"
"Content-Length: 0\r\n\r\n";

const char *NOT_FOUND =
"HTTP/1.1 404 Not Found\r\n"
"Connection: close\r\n"
"Content-Length: 0\r\n\r\n";

const char *UNAUTHORIZED =
"HTTP/1.1 401 Unauthorized\r\n"
"Connection: close\r\n"
"Content-Length: 0\r\n\r\n";

const char *NO_CONTENT =
"HTTP/1.1 204 No Content\r\n"
"Connection: close\r\n"
"Content-Length: 0\r\n\r\n";

int parse_http_request(char *req, char **method, char **path, char **ws_key) {
	*method = strtok(req, " \t\r\n");
	*path = strtok(NULL, " \t\r\n");
	if (!*method || !*path) return -1;
	*ws_key = NULL;
	char *line = NULL;
	while ((line = strtok(NULL, "\r\n"))) {
		if (strncasecmp(line, "Sec-WebSocket-Key:", 18) == 0) {
			char *p = line + 18;
			while (*p == ' ' || *p == '\t') p++;
			*ws_key = p;
		}
	}
	return 0;
}

int get_header_value(const char *req, const char *name, char *out, int out_sz) {
	size_t nlen = strlen(name);
	const char *p = req;
	while ((p = strcasestr(p, name)) != NULL) {
		if ((p == req || (p > req + 1 && p[-2] == '\r' && p[-1] == '\n')) &&
            strncasecmp(p, name, nlen) == 0 && p[nlen] == ':') {
			    p += nlen + 1;
			    while (*p == ' ' || *p == '\t') p++;
			    const char *e = strstr(p, "\r\n");
			    if (!e) e = p + strlen(p);
			    int len = (int)(e - p);
			    if (len >= out_sz) len = out_sz - 1;
			    memcpy(out, p, (size_t)len);
			    out[len] = '\0';
			    return 1;
		    }
		p += nlen;
	}
	return 0;
}

int get_content_length(const char *req) {
	char buf[32];
	if (!get_header_value(req, "Content-Length", buf, sizeof(buf))) return -1;
	return atoi(buf);
}